server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://111.230.251.119:3306/findjob
    username: findjob
    password: 125512
    driver-class-name: com.mysql.jdbc.Driver
  servlet:
    multipart:
      enabled: true
      max-file-size: 20Mb
mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: xyz.huanxicloud.findjob.pojo
#  spring
#  http.multipart.maxFileSize=100Mb
#  spring.http.multipart.maxRequestSize=100Mb
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
