server:
  port: 8080

spring:
  datasource:
    url: jdbc:sqlserver://localhost;database=findjob
    username: findjob
    password: qQ1223334444`
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  servlet:
    multipart:
      enabled: true
      max-file-size: 10Mb
mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: xyz.huanxicloud.findjob.pojo
#  spring
#  http.multipart.maxFileSize=100Mb
#  spring.http.multipart.maxRequestSize=100Mb
pagehelper:
  helperDialect: sqlserver
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
