server:
  port: 8080

spring:
  datasource:
    url: jdbc:jtds:sqlserver://w1.zhexi.tech:56148/findjob
    username: findjob
    password: qQ1223334444@
    driver-class-name: net.sourceforge.jtds.jdbc.Driver
  servlet:
    multipart:
      enabled: true
      max-file-size: 10Mb
mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: xyz.huanxicloud.findjob.pojo
#  spring
#  http.multipart.maxFileSize=100Mb
#  spring.http.multipart.maxRequestSize=100Mb
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
